import { describe, it, expect } from 'vitest';
import {
  generateReportHead,
  generateReportHero,
  generateStatCards,
  generateTable,
  generateIssueSummary,
  generateReportFooter,
  wrapInCard,
  generateCompleteReport,
  generateStandardHtmlReport,
} from '../../src/utils/report-formatters';

describe('Report Formatters', () => {
  const options = {
    title: 'Test Report',
    packageName: 'core',
    version: '1.0.0',
    emoji: '🧪',
  };

  it('generateReportHead should return valid HTML head', () => {
    const head = generateReportHead('My Title');
    expect(head).toContain('<!DOCTYPE html>');
    expect(head).toContain('<html lang="en">');
    expect(head).toContain('<title>My Title</title>');
    expect(head).toContain('<style>');
  });

  it('generateReportHero should return hero section', () => {
    const hero = generateReportHero('Main Title', 'Sub Title');
    expect(hero).toContain('<div class="hero">');
    expect(hero).toContain('<h1>Main Title</h1>');
    expect(hero).toContain('<p>Sub Title</p>');
  });

  it('generateStatCards should return cards grid', () => {
    const cards = [
      { value: 10, label: 'Metric A', color: 'red' },
      { value: '20%', label: 'Metric B' },
    ];
    const html = generateStatCards(cards);
    expect(html).toContain('<div class="stats">');
    expect(html).toContain('<div class="stat-card">');
    expect(html).toContain('color: red');
    expect(html).toContain('10');
    expect(html).toContain('Metric A');
  });

  it('generateTable should return a table', () => {
    const config = {
      headers: ['H1', 'H2'],
      rows: [
        ['R1C1', 'R1C2'],
        ['R2C1', 'R2C2'],
      ],
    };
    const html = generateTable(config);
    expect(html).toContain('<table>');
    expect(html).toContain('<thead>');
    expect(html).toContain('<th>H1</th>');
    expect(html).toContain('<td>R1C1</td>');
  });

  it('generateIssueSummary should return summary card', () => {
    const html = generateIssueSummary(1, 2, 3, 1000);
    expect(html).toContain('Critical: 1');
    expect(html).toContain('Major: 2');
    expect(html).toContain('Minor: 3');
    expect(html).toContain('<strong>Potential Savings: </strong>1,000 tokens');
  });

  it('generateReportFooter should return footer', () => {
    const footer = generateReportFooter({
      ...options,
      packageUrl: 'https://github.com/aiready',
      bugUrl: 'https://github.com/aiready/issues',
    });
    expect(footer).toContain('footer');
    expect(footer).toContain(
      'Generated by <strong>@aiready/core</strong> v1.0.0'
    );
    expect(footer).toContain('https://github.com/aiready');
  });

  it('wrapInCard should wrap content', () => {
    const html = wrapInCard('some content', 'My Card');
    expect(html).toContain('<div class="card">');
    expect(html).toContain('<h2>My Card</h2>');
    expect(html).toContain('some content');
  });

  it('generateCompleteReport should assemble components', () => {
    const html = generateCompleteReport(options, '<p>Hello</p>');
    expect(html).toContain('<!DOCTYPE html>');
    expect(html).toContain('<body>');
    expect(html).toContain('<p>Hello</p>');
    expect(html).toContain('footer');
  });

  it('generateStandardHtmlReport should return a full report', () => {
    const html = generateStandardHtmlReport(
      options,
      [{ value: 100, label: 'Score' }],
      [{ title: 'Section 1', content: 'Content 1' }],
      { value: 85, label: 'Overall' }
    );
    expect(html).toContain('AIReady Test Report');
    expect(html).toContain('score-card');
    expect(html).toContain('85');
    expect(html).toContain('Overall');
    expect(html).toContain('Section 1');
  });
});
